version: "2.2"
services:
  node:
    cpus: 0.5
    cpu_percent: 50
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: burger_builder/node
    container_name: buger_builder_node
    ports:
      - "3000:3000"
    volumes:
      - ..:/var/www/burger-builder
    networks:
      - burger_builder
networks:
  burger_builder:
    driver: bridge
      