version: "3"
services:
  node:
    build:
      dockerfile: docker/Dockerfile
      context: ..
    image: burger_builder/node
    container_name: buger_builder_node
    ports:
      - "3000:3000"
    volumes:
      - ..:/var/www/burger-builder
    networks:
      - burger_builder
networks:
  burger_builder:
    driver: bridge
      